# Generated by Django 4.0.4 on 2022-06-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades_comunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('autor', models.CharField(max_length=40)),
                ('fecha_en_que_se_escribio', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Historia_comunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('autor', models.CharField(max_length=40)),
                ('fecha_en_que_se_escribio', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Informacion_sobre_mi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=40)),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField()),
            ],
        ),
    ]
