# Generated by Django 4.0.4 on 2022-07-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mochilas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=1000)),
                ('precio', models.IntegerField()),
                ('codigo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Totebags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Actividades_comunidad',
        ),
        migrations.DeleteModel(
            name='Historia_comunidad',
        ),
        migrations.DeleteModel(
            name='Informacion_sobre_mi',
        ),
    ]
